### ISSUE TITLE
[서비스 연동] API Gateway 서버 CORS 에러

### ISSUE THREAD

**Issue by hwamoc** [OIDC2020-watermelon/BackEnd#136]
**증상**  
API Gateway 서버로 각 서비스들을 호출시 CORS 에러 발생
`Access localhost:1... to XMLHttpRequest at 'http://gateway.url/auth/*..' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'http://*...., http://*....', but only one is allowed.`

zuul은 디폴트 값으로 CORS를 허용하는데
각 서비스들도 CORS를 허용하므로 헤더에 값들이 두번씩 중복되어 발생한 문제였다.

**해결 시나리오**  
1. zuul server의 application.yml 파일에 
`ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin` 추가
2. 다시 배포 

**예상 시나리오**  
gateway url로 각 서비스들 api 요청시 200 응답

**환경 (please complete the following information):**  
 - OS: macOS Catalina
 - Browser: chrome

**Comment by kindcompany** [comment]
Very Thanksful, hwamoc!
It really worked for me. And the detailed solution to restart the zuul server, truely worked.

**Comment by CompuTaker** [comment]
Very Thanksful, hwamoc! It really worked for me.
And the detailed solution to restart the zuul server, truely worked.
